##### Prefix: Ctrl-a instead of Ctrl-b #####

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config with: Ctrl-a then r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"


##### Good defaults #####

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g status-position bottom

# Better colors / truecolor
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"


##### TPM plugins #####

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Nybkox/tmux-ukiyo'


##### Ukiyo theme: Kanagawa Dragon #####

set -g @ukiyo-theme "kanagawa/dragon"

# Optional styling
set -g @ukiyo-show-powerline true
set -g @ukiyo-show-flags true
set -g @ukiyo-refresh-rate 5
set -g @ukiyo-left-icon session
set -g @ukiyo-border-contrast true

# Optional status modules
set -g @ukiyo-plugins "git cpu-usage ram-usage time"

# Time format
set -g @ukiyo-military-time true
set -g @ukiyo-time-format "%F %R"
set -g @ukiyo-ignore-window-colors true


##### Keep TPM at the very bottom #####

run '~/.tmux/plugins/tpm/tpm'
